samples:
    "simonsSS6004478.srt.aln.bam"
    "simonsLP6005441-DNA_A01.srt.aln.bam"
    "simonsLP6005443-DNA_A12.srt.aln.bam"
    "simonsLP6005442-DNA_C10.srt.aln.bam"
    "simonsLP6005442-DNA_A02.srt.aln.bam"
